---
title: "R04c-stroke_type_consolidation"
author: "James Farrell (james.farrell@hdruk.ac.uk)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    number_sections: true
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

library(tidyverse)
library(kableExtra)
library(finalfit)

dir.create(here::here("outputs", "R04c-stroke_type_consolidation"), recursive = TRUE)

source(here::here("R", "R00-functions.R"))

```

# Load datasets

```{r}

cohort = read_rds(here::here("data", "cohort_cleaned.rds"))

```

# Prepare

## Compute 'overall' and 'no record in source' categories

```{r}

cohort = cohort %>% 
  mutate(
    overall = 1,
    ssnap_no_record = is.na(ssnap_ischaemic) & is.na(ssnap_haemorrhagic) & is.na(ssnap_missing),
    hes_apc_no_record = is.na(hes_apc_ischaemic) & is.na(hes_apc_haemorrhagic) & is.na(hes_apc_nos),
    gdppr_no_record = is.na(gdppr_ischaemic) & is.na(gdppr_haemorrhagic) & is.na(gdppr_nos),
    deaths_no_record = is.na(deaths_ischaemic) & is.na(deaths_haemorrhagic) & is.na(deaths_nos),
  )

```

## Code-level dataset

```{r}


cohort_long = cohort %>% 
  select(row_id, person_id, index_stroke_date, stroke_fatality, stroke_type_harmonised,
         overall,
         ssnap_ischaemic, ssnap_haemorrhagic, ssnap_missing, ssnap_no_record,
         hes_apc_ischaemic, hes_apc_haemorrhagic, hes_apc_nos, hes_apc_no_record,
         gdppr_ischaemic, gdppr_haemorrhagic, gdppr_nos, gdppr_no_record,
         deaths_ischaemic, deaths_haemorrhagic, deaths_nos, deaths_no_record,
         stroke_code_list, stroke_description_list, stroke_source_list, stroke_type_list) %>% 
  mutate(
    code = stroke_code_list %>% 
      str_extract_all('(?<=\\["|,")[^\\"]+(?=",|"\\])'),
    description = stroke_description_list %>% 
      str_extract_all('(?<=\\["|,")[^\\"]+(?=",|"\\])'),
    stroke_type = stroke_type_list %>% 
      str_extract_all('(?<=\\["|,")[^\\"]+(?=",|"\\])'),
    source = stroke_source_list %>% 
      str_extract_all('(?<=\\["|,")[^\\"]+(?=",|"\\])'),
  ) %>% 
  unnest(code, description, stroke_type, source)



```

# Breakdown of consolidated stroke type 

```{r}

stroke_type_breakdown = cohort_long %>%
  mutate(
    total_records = n(),
    total_individuals = n_distinct(person_id)
  ) %>% 
  group_by(stroke_type_harmonised, source, stroke_type, code, description, total_records, total_individuals) %>% 
  summarise(
    n_records = n(),
    n_individuals = n_distinct(person_id) 
  ) %>%
  ungroup() %>% 
  mutate(across(
    c(total_records, total_individuals, n_records, n_individuals),
    ~case_when(
      . < 10 ~ 0,
      TRUE ~ plyr::round_any(., 5)
    )
  ))

write_csv(
  x = stroke_type_breakdown,
  file = here::here("outputs", "R04c-stroke_type_consolidation", "stroke_type_breakdown.csv")
)



```

