---
title: "R12-home_time"
author: "James Farrell (james.farrell@hdruk.ac.uk)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    number_sections: true
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.width=9, fig.height=5.5) 

dir.create(here::here("outputs", "R12-home_time"), recursive = TRUE)

source(here::here("R", "R00-functions.R"))
library(tidyverse)
library(lubridate)
library(finalfit)
library(emmeans)
library(rlang)
library(sandwich)
library(lmtest)
library(broom)
library(broom.helpers)
library(rstatix)
library(patchwork)

```

# Load datasets

```{r}

cohort = read_rds(here::here("data", "cohort_cleaned.rds"))

# Create overall flag ----
cohort = cohort %>% 
  mutate(
    overall = "Overall" %>% 
      ff_label("Overall")
  )

# Dependant and explanatory variables ----
dependent_var = "home_time"

explanatory_var = c(
  "year_of_stroke",
  "age_group", "sex", "imd_19_quintile", "ethnicity", "region", "cci_fct",
  "data_source_combination_ex_deaths", "nihss_arrival_fct",
  "rankin_at_discharge_fct"
)

vlabels = extract_variable_label(cohort)

```

# Compute statistics

## Filter cohorts

```{r}


cohort_types = list(
  "All stroke types" = "all_types",
  "Ischaemic or unknown" = "ischaemic_or_unknown",
  "Haemorrhagic" = "haemorrhagic"
)


cohorts = cohort_types %>%
  map(.f = function(.cohort_type){
    
    .cohort = cohort %>% 
      filter(stroke_ssnap == 1 | stroke_hes_apc == 1 | stroke_gdppr == 1) %>% 
      # Non-fatal strokes and hosptial survivors
      filter(stroke_fatality == "Non-fatal") %>%
      filter(
        is.na(discharge_date) | (date_of_death > discharge_date) | is.na(date_of_death)
      ) %>% 
      filter(is.na(rankin_at_discharge_fct) | (rankin_at_discharge_fct != "6")) %>% 
      mutate(rankin_at_discharge_fct = fct_drop(rankin_at_discharge_fct))
      
    
    if (.cohort_type == "ischaemic_or_unknown"){
      
      .cohort = .cohort %>% 
        filter(stroke_type_harmonised %in% c("Ischaemic", "Unknown"))
      
    } else if (.cohort_type == "haemorrhagic"){
      
      .cohort = .cohort %>% 
        filter(stroke_type_harmonised == "Haemorrhagic")
      
    }

    return(.cohort)
  })

```

## Multivariable linear regression

### Fit models

```{r}

lm_models = cohorts %>% 
  map(.f = function(.cohort){
    
    model_formula = as.formula(paste0(dependent_var, " ~ ", paste0(explanatory_var, collapse = " + ")))
    lm_model = lm(model_formula, .cohort)
    
  })

```


### Model coefficients

```{r}


model_coeffs = lm_models %>% 
  imap_dfr(.f = function(.lm_model, .stroke_type){
    
    model_coeff = .lm_model %>% 
      tidy_and_attach(conf.int = TRUE) %>%
      tidy_add_reference_rows() %>% 
      tidy_add_variable_labels() %>%
      tidy_add_term_labels() %>% 
      mutate(stroke_type = .stroke_type) %>% 
      relocate(stroke_type)
    
  })

write_csv(
  model_coeffs,
  here::here("outputs", "R12-home_time", "home_time_model_coeffs.csv")
)

```

### Model fit statistics


```{r}


model_stats = lm_models %>% 
  imap_dfr(.f = function(.lm_model, .stroke_type){
    
    model_stat = .lm_model %>% 
      glance() %>% 
      mutate(stroke_type = .stroke_type) %>% 
      relocate(stroke_type)
    
  })

model_stats = model_stats %>%
  janitor::clean_names() %>% 
  select(-c(df_residual, deviance, sigma)) %>% 
  mutate(
    nobs = case_when(
      nobs < 10 ~ 0,
      TRUE ~ plyr::round_any(nobs, 5)
    )
  )

write_csv(
  model_stats,
  here::here("outputs", "R12-home_time", "home_time_model_stats.csv")
)

```

## Unadjusted Means

```{r}

unadjusted_means = cohorts %>% 
  imap_dfr(.f = function(.cohort, .stroke_type){
    
    unadjusted_mean = c("overall", explanatory_var) %>% 
      map_dfr(
        .f = function(.var){
          
          .cohort %>% 
            group_by(!!sym(.var)) %>% 
            get_summary_stats(
              "home_time" , type = c("full"),
              show = c("n", "mean", "sd", "ci")
            ) %>% 
            ungroup() %>% 
            mutate(
              n = case_when(
                n < 10 ~ 0,
                TRUE ~ plyr::round_any(n, 5)
              ),
              stroke_type = .stroke_type,
              variable = .var,
              var_label = vlabels[.var],
              adjustment = "none",
              lower_ci = mean - ci,
              upper_ci = mean + ci,
              pct = n / sum(n)
            ) %>% 
            rename(label = !!sym(.var)) %>%
            mutate(term = paste0(variable, label)) %>% 
            select(stroke_type, adjustment, term, variable, var_label, label,
                   n, pct, mean, sd, lower_ci, upper_ci)
        }
      )
  })


write_csv(
  unadjusted_means,
  here::here("outputs", "R12-home_time", "home_time_unadjusted_means.csv")
)

```

## Adjusted Means

```{r}

adjusted_means = lm_models %>% 
  imap_dfr(.f = function(.lm_model, .stroke_type){
    
    adjusted_mean = explanatory_var %>% 
      map_dfr(
        .f = function(.var){
          
          
          emmean_object = emmeans(
            object = .lm_model,
            specs = as.formula(paste0("~", .var)),
            weights = "proportional",
            nuisance = explanatory_var[explanatory_var != .var]
          )  
          
          table_emmean = emmean_object %>%
            as_tibble() %>%
            janitor::clean_names() %>% 
            rename(
              label = !!sym(.var),
              mean = emmean,
              upper_ci = upper_cl,
              lower_ci = lower_cl
            ) %>%
            mutate(
              stroke_type = .stroke_type,
              adjustment = "adjusted",
              variable = .var,
              var_label = vlabels[.var],
              term = paste0(variable, label)
            ) %>% 
            select(stroke_type, adjustment, term, variable, var_label, label, mean, lower_ci, upper_ci)
          
          return(table_emmean)
        }
      )
    
  })

write_csv(
  adjusted_means,
  here::here("outputs", "R12-home_time", "home_time_adjusted_means.csv")
)


```

# Formatted Results

## Unadjusted and Adjusted Means

```{r}

combined_means = unadjusted_means %>% 
  mutate(row_id = row_number()) %>% 
  full_join(
    adjusted_means %>% 
      select(stroke_type, term, adj_mean = mean, adj_lower_ci = lower_ci, adj_upper_ci = upper_ci)
  ) %>% 
  mutate(
    mean_tidy = paste0(
      round_tidy(mean, 1), " (", round_tidy(lower_ci, 1), ", ", round_tidy(upper_ci, 1), ")"
    ),
    adj_mean_tidy = case_when(
      is.na(adj_mean) ~ "-",
      TRUE ~ paste0(
        round_tidy(adj_mean, 1), " (", round_tidy(adj_lower_ci, 1), ", ", round_tidy(adj_upper_ci, 1), ")"
      )
    ),
    n_pct_tidy = paste0(n, " (", round_tidy(pct*100, 1), ")")
  ) %>% 
  select(stroke_type, term, variable, var_label, label, n_pct_tidy, mean_tidy, adj_mean_tidy) %>% 
  pivot_wider(
    names_from = stroke_type,
    values_from = c(n_pct_tidy, mean_tidy, adj_mean_tidy)
  ) %>% 
  group_by(variable) %>% 
  mutate(var_index = row_number()) %>% 
  ungroup() %>% 
  mutate(var_label = if_else(var_index == 1, var_label, "")) 

combined_means = combined_means %>%
  select(
    var_label, label,
    
    n_all = `n_pct_tidy_All stroke types`,
    mean_all = `mean_tidy_All stroke types`,
    adj_mean_all = `adj_mean_tidy_All stroke types`,
    
    n_ischaemic_unknown = `n_pct_tidy_Ischaemic or unknown`,
    mean_ischaemic_unknown = `mean_tidy_Ischaemic or unknown`,
    adj_mean_ischaemic_unknown = `adj_mean_tidy_Ischaemic or unknown`,
    
    n_haemorrhagic = `n_pct_tidy_Haemorrhagic`,
    mean_haemorrhagic = `mean_tidy_Haemorrhagic`,
    adj_mean_haemorrhagic = `adj_mean_tidy_Haemorrhagic`,
    
  )

write_csv(
  combined_means,
  here::here("outputs", "R12-home_time", "home_time_combined_means.csv")
)


combined_means %>% 
  mykable(
    col.names = c(
      "Variable", "Level",
      "n (%)", "Unadjusted mean", "Adjusted Mean",
      "n (%)", "Unadjusted mean", "Adjusted Mean",
      "n (%)", "Unadjusted mean", "Adjusted Mean"
      )
  ) %>% 
  kableExtra::add_header_above(
    c(" ", " ", "All stokes types" = 3, "Ischaemic or unknown" = 3, "Haemorrhagic" = 3)
  )


```

## Regression Model Coefficients

```{r}

model_coeffs_tidy = model_coeffs %>% 
  mutate(
    stroke_type = case_when(
      stroke_type == "All stroke types" ~ "all",
      stroke_type == "Ischaemic or unknown" ~ "ischaemic_unknown",
      stroke_type == "Haemorrhagic" ~ "haemorrhagic"
    ),
    coef_tidy = case_when(
      is.na(estimate) ~ "-",
      TRUE ~ paste0(
        round_tidy(estimate, 2), " ([", round_tidy(conf.low, 2), ", ",
        round_tidy(conf.high, 2), "], p", p_tidy(p.value, 3), ")"
      )
    )
  ) %>% 
  select(stroke_type, term, variable, var_label, label, coef_tidy) %>% 
  pivot_wider(
    names_from = stroke_type,
    values_from = coef_tidy
  ) %>% 
  group_by(variable) %>% 
  mutate(var_index = row_number()) %>% 
  ungroup() %>% 
  mutate(var_label = if_else(var_index == 1, var_label, ""))
  
  
model_coeffs_tidy %>%
  select(var_label, label, all, ischaemic_unknown, haemorrhagic) %>% 
  mykable(
    col.names = c(
      "Variable", "Level",
      "All stroke types",
      "Ischaemic or unknown",
      "Haemorrhagic"
      )
  )


```

# Plot


```{r fig.height=9, fig.width=9}


home_time_plot = unadjusted_means %>% 
  bind_rows(adjusted_means)

home_time_plot = home_time_plot %>% 
  mutate(
    adjustment = adjustment %>% 
      factor() %>% 
      fct_recode(
        "Adjusted" = "adjusted",
        "Unadjusted" = "none"
      ) %>% 
      fct_relevel("Unadjusted"),
    term = term %>% 
      factor() %>% 
      fct_inorder() %>% 
      fct_rev()
  )


fig_plot = home_time_plot %>% 
  ggplot(aes(x = mean, xmin = lower_ci, xmax = upper_ci,
             y = term,
             colour = adjustment)) +
  geom_linerange() +
  geom_point() +
  facet_wrap(~stroke_type) +
  scale_x_continuous(limits = c(0, 180), breaks = seq(0, 180, by = 30)) +
  scale_y_discrete(labels = rev(unadjusted_means$label)) +
  scale_color_brewer(palette = "Dark2") +
  labs(y = NULL, x = NULL, colour = "Mean home-time (days)") +
  theme_bw() +
  theme(
    plot.margin = margin(5, 5, 5, 5),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_blank(),  # Remove major y gridlines
    panel.grid.minor.y = element_blank(),  # Remove minor y gridlines
    legend.position = "bottom",  # Position legend at the bottom
    legend.box = "horizontal",   # Ensure the legend box is horizontal
    strip.background = element_rect(fill = "grey97", color = "black")
  ) +
  geom_hline(
    yintercept = c(7.5, 13.5, 20.5, 24.5, 33.5, 39.5, 44.5, 46.5, 51.5, 55.5),
    linetype = "dashed",
    colour = "grey50",
    linewidth = 0.3
  )


table_plot_var = home_time_plot %>%
  filter(stroke_type == "All stroke types", adjustment == "Unadjusted") %>% 
  select(variable, var_label, label, term) %>% 
  group_by(variable) %>% 
  mutate(variable_plot = if_else(row_number() == 1, var_label, ""))
  
table_plot = table_plot_var %>% 
  ggplot(aes(y = term)) + 
  geom_text(aes(x = 0, label = variable_plot), size = 3.25, hjust = 0, vjust = 0.5, fontface = "bold") +
  geom_text(aes(x = 1, label = ""), hjust = 0, fontface = "bold") + 
  labs(x = "", y = "") +
  theme_void() +
  theme(
    plot.margin = margin(5, 5, 5, 5),
    panel.grid.major =  element_blank()
  )


combined_plot = (table_plot | fig_plot) + 
  plot_layout(widths = c(1, 3), heights = c(4, 1)) +
  plot_annotation(title = "180-day Home-Time from Stroke Onset" ) &
  theme(
    plot.title = element_text(face = "bold", size = 16)
  )

combined_plot

ggsave(
  here::here("outputs", "R12-home_time", "home_time_combined.png"),
  plot = combined_plot,
  height = 9,
  width = 9,
  dpi = 300
)



```

